[package]
name = "cw4"
version = "1.0.1"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2021"
description = "CosmWasm-4 Interface: Groups Members"
license = "Apache-2.0"
repository = "https://github.com/CosmWasm/cw-plus"
homepage = "https://cosmwasm.com"

[dependencies]
cw-storage-plus = "1.0.1"
cosmwasm-schema = "1.1.0"
cosmwasm-std = "1.1.0"
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
