---
name: Build and Push ECR

on:
  release:
    types:
      - published

jobs:
  fusiond:
    runs-on: devops-prod
    if: startsWith(github.ref_name, 'fusiond@')
    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: eu-west-1
      - uses: aws-actions/amazon-ecr-login@v2
        id: ecr
        with:
          registries: ${{ secrets.ECR_REGISTRY }}
      - name: Set tags
        id: vars
        run: |
          echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV
          echo "COMMIT_SHA=$(git rev-parse HEAD)" >> $GITHUB_ENV
          echo "BUILD_DATE=$(git show -s --format=%ci ${{ env.COMMIT_SHA }})" >> $GITHUB_ENV
          echo "TAG=$(echo ${GITHUB_REF_NAME} | cut -d'@' -f2)" >> $GITHUB_ENV
          echo "ECR_REPO=${{ secrets.ECR_REGISTRY }}.dkr.ecr.eu-west-1.amazonaws.com/qredo/production/fusionchain">> $GITHUB_ENV
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and Push
        id: image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile-fusiond
          build-args: |
             SERVICE=fusiond
             GIT_SHA=${{ env.COMMIT_SHA }}
             BUILD_DATE=${{ env.BUILD_DATE }}
          push: true
          tags: |
            ${{ env.ECR_REPO }}:${{ env.SHORT_SHA }}
            ${{ env.ECR_REPO }}:${{ env.TAG }}
            ${{ env.ECR_REPO }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
