# Checks if a changelog is missing in the PR diff
name: Changelog Reminder
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    paths: ["**/*.go", "**/*.ts", "**/*.tsx"]
permissions:
  pull-requests: write
jobs:
  remind:
    name: Changelog Reminder
    runs-on: ubuntu-latest
    # Skip draft PRs and PRs starting with: revert, test, chore, ci, docs, style, build, refactor
    if: "!github.event.pull_request.draft && !contains(github.event.pull_request.title, 'revert') && !contains(github.event.pull_request.title, 'test') && !contains(github.event.pull_request.title, 'chore') && !contains(github.event.pull_request.title, 'ci') && !contains(github.event.pull_request.title, 'docs') && !contains(github.event.pull_request.title, 'style') && !contains(github.event.pull_request.title, 'build') && !contains(github.event.pull_request.title, 'refactor')"
    steps:
      - uses: actions/checkout@v6
      - uses: mskelton/changelog-reminder-action@v3
        with:
          message: |
            Hey @${{ github.actor }} and thank you for opening this pull request! ğŸ‘‹ğŸ¼

            It looks like you forgot to add a changelog entry for your changes. Make sure to add a changelog entry in the 'CHANGELOG.md' file.

