---
name: semantic_release

on:
  workflow_run:
    workflows:
      - push
    types:
      - completed

jobs:
  release:
    name: Release
    if: ${{ github.ref == 'refs/heads/master' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: devops-prod
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Generate a token
        id: generate_token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - name: Multi-semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.generate_token.outputs.token }}
          GIT_AUTHOR_EMAIL: 'semanticrelease@qredo.com'
          GIT_COMMITTER_EMAIL: 'semanticrelease@qredo.com'
          GIT_AUTHOR_NAME: '@semanticrelease'
          GIT_COMMITTER_NAME: '@semanticrelease'
        run: npx -p @qiwi/semrel-toolkit multi-semrel
